# https://sap.github.io/jenkins-library/
general:
  gitSshKeyCredentialsId: '#{jenkins_git_creds}'
  collectTelemetryData: false
steps:
  setupCommonPipelineEnvironment:
    collectTelemetryData: false
  mtaBuild:
    buildTarget: 'CF'
    defaultNpmRegistry: 'https://registry.npmjs.org/'
  cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    cloudFoundry:
      apiEndpoint: 'https://api.cf.#{jenkins_cf_region}.hana.ondemand.com'
      org: '#{jenkins_cf_org}'
      space: '#{jenkins_cf_space}'
      credentialsId: '#{jenkins_cf_creds}'
      dockerImage: 's4sdk/docker-cf-cli'
      dockerWorkspace: '/home/jenkins/piper'
    mtaDeployParameters: '-f -e mta_to_cf.mtaext'
  mailSendNotifiction:
    notificationAttachment: true
    notificationRecipients: 'andrew.lunde@sap.com'
    notifyCulprits: false
  slackSendNotification:
    credentialsId: 'SLACKSECRET'
    channel: '#jenkins_builds'
